### ISSUE TITLE
Reviews of design doc

### ISSUE THREAD

**Issue by aracpyon** [danbourdier/TriHarder#1]
Hey Daniel! Great job on your design doc in a short period of time! Here are my reviews:

**MVPs**
- [x] please follow a/A MVP guidelines [https://open.appacademy.io/learn/swe-in-person-nyc/full-stack-project/mvp-checklist](url) as follows:

MapMyRun
- Making running routes using map
- Friending
- Comments on runs
- Dashboard that tracks completed runs
- Bonus: cheers for friends
- Bonus: Search for runs by location
- Bonus: goals

- [x] `Search` MVP is a bonus quest. Take `Search` off your 3rd MVP. 
- [x] put `Friends` MVP as your 4th. 
- [x] `Dashboard that tracks completed runs` is your profile. 
- [x] Be specific what is `gear` MVP for. If it's not a functionality of the original app, let's think about it later until we finish most main features

**Schema**
- [x] `Workouts` table can break into two tables `routes` and `workouts`. Reorganize the table. The main functionality of MapMyRun is tracking the routes. `routes` should be the main table and `workouts` table is for saving the `completed route` data, with foreign keys of `user_id` and `route_id`
- [x] I still don't understand what `gear` is for(I guess it's for foorwear?). Let's consider this until we finish all main functionalities. We can discuss this more later during our full stack meeting. 
- [x] If we have `workouts` table, we might not need `status` table. 
- [x] `likes`: this is bonus feature, so we don't have to put too much thoughts on this yet. The best example for like is `Art API` project. This table needs to be rewritten but let's put `(bonus)` on it and think about it later. 
- [x] `comments`: get rid of `liker_id`. 
- [ ] `comments`: think about on which posts you are adding comment functionality. If you are adding comments on both `routes`, `workouts` and `status`, consider to use `polymorphism`. 

**state**
- [x] please change your state based on your changes on schema

**Comment by danbourdier** [comment]
Recommended changes made!
