### ISSUE TITLE
2nd review of schema and states

### ISSUE THREAD

**Issue by aracpyon** [danbourdier/TriHarder#2]
**schema**
- [x] please put  your mvp 6.`create account, login, logout...` as your 1st MVP. (This is what you are going to do on the first day of fullstack project)
- [x] combine your `workout` and `status` tables into one table. (choose one of the names)

**state**
- [x] please reflect the above changed on the state. ex. now that workout and status tables are in one table, their states should be one too.

**Comment by danbourdier** [comment]
Changes made!
