### ISSUE TITLE
Backend and frontend routes 

### ISSUE THREAD

**Issue by aracpyon** [danbourdier/TriHarder#3]
Great job on your routes! Here are my reviews:

**Backend**
Looks good so far

**frontend**
- [ ] is `/dashboard` the page that shows all the routes? If so, I think we can show `actvity_feed` on your dashboard. That way you don't need to create another route for `activity_feed`

**Comment by danbourdier** [comment]
<img width="962" alt="Screen Shot 2020-06-01 at 2 04 55 PM" src="https://user-images.githubusercontent.com/57198255/83439299-e2386480-a410-11ea-81ef-19d2f5942484.png">
Dashboard is one of the 3 tabs on our home_page so if i moved one of them i would be unintentionally separating mutual concerns. If that makes sense
